# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.12
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
    -   id: ruff-check              # Run the linter
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
    -   id: ruff-format             # Run the formatter
        types_or: [ python, pyi, jupyter ]
